first working version of ndec-b

diff --git a/ndec-b b/ndec-b
--- a/ndec-b
+++ b/ndec-b
@@ -132,7 +132,43 @@ INPUT-LIST                       * if INPUT-LIST is a text file:
 #                 command completes
 #   --dryrun: show commands but do not run
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-PARALLEL="parallel --no-run-if-empty -j ${NJOBS-20} --linebuffer ${DRYRUN}"
+PARALLEL="parallel --no-run-if-empty -j ${NJOBS-5} --linebuffer ${DRYRUN}"
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Get mcnp executable in PATH.
+# If not present, exit with ERROR.
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+[[ -x $MCNP ]] || export MCNP=$(which mcnp6)
+[[ -x $MCNP ]] || export MCNP=$(which mcnp)
+[[ -x $MCNP ]] || {>&2 echo -e "ERROR: could not find njoy executable file in PATH. Add executable to path with either name 'mcnp6' or 'mcnp'"; exit 1;}
+
+
+
+#######################################################################
+#######################################################################
+#                                                                     #
+#                           FUNCTIONS                                 #
+#                                                                     #
+#######################################################################
+#######################################################################
+run_mcnp_parallel () {
+#=== FUNCTION =========================================================
+# NAME: run_mcnp_parallel
+# DESCRIPTION: Run MCNP calculation for given input and xsdir.
+# PARAMETER 1: input file (absolute path)
+# PARAMETER 2: xsdir file (absolute path)
+#======================================================================
+MCNP_INPUT="$1"
+MCNP_XSDIR="$2"
+name_input=$(basename "$MCNP_INPUT")
+name_xsdir=$(basename "$MCNP_XSDIR")
+WDIR="RUN_${name_input}"
+[[ ! -d "$WDIR" ]] && mkdir -p "$WDIR"
+printf "INPUT: %-30s\tXSDIR: %-20s ..... START at %s\n" $(basename "$MCNP_INPUT") $(basename "$MCNP_XSDIR") $(date +"%T")
+(
+cd "$WDIR" && "$MCNP" i="$MCNP_INPUT" n="${name_input}." xsdir="$MCNP_XSDIR" tasks ${NTASKS-4} &> "${name_input}.log"
+)
+printf "INPUT: %-30s\tXSDIR: %-20s ..... END at %s\n" $(basename "$MCNP_INPUT") $(basename "$MCNP_XSDIR") $(date +"%T")
+}
 
 
 
@@ -174,218 +210,14 @@ done
 # Default is pwd.
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 read -p "Enter the target working directory [.]: " CWD
-export CWD="${CWD:-$(pwd)}"
-mkdir -p "$CWD"
+CWD="$(realpath ${CWD:-$(pwd)})"
+[[ -d "$CWD" ]] || { mkdir -p "$CWD";echo "Make working directory '$CWD'"; }
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # Get XSDIR file.
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 read -p "Provide the XSDIR file: " XSDIR
+XSDIR="$(realpath $XSDIR)"
 [[ -s "$XSDIR" ]] || {>&2 echo -e "ERROR: empty or non-existing XSDIR file.";exit 1;}
-
-
-
-
-echo -e "\nCheck xsdir entries for benchmark suite..."
-for file in ${FILELIST[@]}
-do
-   ISO=( $(grep -oh "^[^c].*[0-9]\{5\}\.03[cC]" "$file" | grep -o "[0-9]\{5\}\.03[cC]" | sort | uniq | cut -d. -f1) )
-   for iso in ${ISO[@]}
-   do
-      COUNT=$(grep -c "${iso}\.03[cC]" "$XSDIR")
-      [[ $COUNT -lt 1 ]] && {>&2 echo -e "ERROR: Missing entry for '${iso}.03c' in xsdir file.";exit 1;}
-   done
-done
-echo -en "\e[1A"; echo -e "\e[0K\rAll requested xsdir entries for benchmark suite are present."
-exit
-
-
-
-
-###########################################################
-# Setup input options by parsing the command line arguments
-###########################################################
-POSITIONAL=()
-while [[ $# -gt 0 ]]
-do
-key="$1"
-case $key in
-    -h|--help)
-    echo -e "$USAGE"
-    exit 0
-    ;;
-    --ace-only)
-    ACEONLY="--ace-only"
-    shift # past argument
-    ;;
-    --run-njoy-parallel)
-    RUNNJOYPARALLEL="$2"
-    shift # past argument
-    shift # past value
-    ;;
-    --run-mcnp-parallel)
-    RUNMCNPPARALLEL="$2"
-    shift # past argument
-    shift # past value
-    ;;
-    -p|--processing)
-    shift # past argument
-    ;;
-    -b|--benchmark-suites)
-    NB="$2"
-    shift # past argument
-    shift # past value
-    for i in $(seq 1 $NB); do BMARKS+=("$1"); shift; done
-    ;;
-    --tasks)
-    TASKS="--tasks $2"
-    shift # past argument
-    shift # past value
-    ;;
-    --max-jobs-mcnp)
-    NMCNP="--max-jobs $2"
-    shift # past argument
-    shift # past value
-    ;;
-    --max-jobs-njoy)
-    NNJOY="--max-jobs $2"
-    shift # past argument
-    shift # past value
-    ;;
-    *)    # unknown option
-    POSITIONAL+=("$1") # save it in an array for later
-    shift # past argument
-    ;;
-esac
-done
-
-
-
-#######################################################################
-#######################################################################
-#                                                                     #
-#                          PROCESS INPUTS                             #
-#                                                                     #
-#######################################################################
-#######################################################################
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Get run-njoy-parallel from command line if given,
-# otherwise search for it in script folder.
-# Otherwise search for it in PATH.
-# If not present, exit with ERROR.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-[[ -x $RUNNJOYPARALLEL ]] || RUNNJOYPARALLEL=$(find "$SCRIPTDIR" -name "run-njoy-parallel" -type f)
-[[ -x $RUNNJOYPARALLEL ]] || RUNNJOYPARALLEL=$(which run-njoy-parallel)
-[[ -x $RUNNJOYPARALLEL ]] || {>&2 echo -e "ERROR: could not find executable file 'run-njoy-parallel'"; exit 1;}
-RUNNJOYPARALLEL="$(realpath $RUNNJOYPARALLEL)"
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Get run-mcnp-parallel from command line if given,
-# otherwise search for it in script folder.
-# Otherwise search for it in PATH.
-# If not present, exit with ERROR.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-[[ -x $RUNMCNPPARALLEL ]] || RUNMCNPPARALLEL=$(find "$SCRIPTDIR" -name "run-mcnp-parallel" -type f)
-[[ -x $RUNMCNPPARALLEL ]] || RUNMCNPPARALLEL=$(which run-mcnp-parallel)
-[[ -x $RUNMCNPPARALLEL ]] || {>&2 echo -e "ERROR: could not find executable file 'run-mcnp-parallel'"; exit 1;}
-RUNMCNPPARALLEL="$(realpath $RUNMCNPPARALLEL)"
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Check if xsdir file is present.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-[[ -z ${POSITIONAL[0]} ]] && {>&2 echo -e "ERROR: Missing xsdir file XSDIR.\n$USAGE";exit 1;} || XSDIR="$(realpath ${POSITIONAL[0]})"
-[[ -s "$XSDIR" ]] || {>&2 echo -e "ERROR: empty or non-existing xsdir file '$XSDIR'.";exit 1;}
-[[ -f "$XSDIR" || -h "$XSDIR" ]] || {>&2 echo -e "ERROR: XSDIR must be a file or a symlink.";exit 1;}
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Save list of ENDF-6 files.
-# Do not run any check, since run-njoy-parallel will do it.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-INPUT_LIST="${POSITIONAL[1]}"
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Process the list of benchmark suites.
-# If the list is not set, use the default benchmarks.
-# Write 5 suites of benchmarks in text files in the current working directory.
-# If the list is set, check that all files exist and are not empty.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-if [[ -z $BMARKS ]]
-then
-   find "/opt/lab/data/inputs/shielding/fns_tof" -maxdepth 1 -type f -o -type l > "list-shielding-fns_tof"
-   find "/opt/lab/data/inputs/shielding/fns_in_situ" -maxdepth 1 -type f -o -type l > "list-shielding-fns_in_situ"
-   find "/opt/lab/data/inputs/shielding/mcnp6_validation" -maxdepth 1 -type f -o -type l > "list-shielding-mcnp6_validation"
-   find "/opt/lab/data/inputs/shielding/oktavian" -maxdepth 1 -type f -o -type l > "list-shielding-oktavian"
-   find "/opt/lab/data/inputs/icsbep/nea" -maxdepth 1 -type f -o -type l > "list-icsbep-123"
-   BMARKS=("list-shielding-fns_tof" "list-shielding-fns_in_situ" "list-shielding-mcnp6_validation" "list-shielding-oktavian" "list-icsbep-123")
-else
-   for B in ${BMARKS[@]}
-   do
-      [[ -s "$B" ]] || {>&2 echo -e "ERROR: empty or non-existing MCNP benchmark suite file '$B'"; exit 1;}
-      [[ -f "$B" || -h "$B" ]] || {>&2 echo -e "ERROR: MCNP benchmark suite '$B' must be a file or a symlink.";exit 1;}
-      for file in $(sed '/^$/d' "$B"); do [[ -s "$file" ]] || {>&2 echo -e "ERROR: empty or non-existing MCNP input file '$file'";exit 1;}; done
-   done
-fi
-echo -e "MCNP input will be taken from the following benchmark lists:"
-for B in ${BMARKS[@]}; do  echo  " - $(realpath $B)"; done
-
-RUNJNOYFOLDER="$(pwd)/processing"
-if [[ ! -z $INPUT_LIST ]]
-then
-   INPUT_LIST="$(realpath $INPUT_LIST)"
-   mkdir -p $RUNJNOYFOLDER
-( cd $RUNJNOYFOLDER && $RUNNJOYPARALLEL "$INPUT_LIST" --xsdir "$XSDIR" $ACEONLY $NNJOY )
-
-
-#######################################################################
-#######################################################################
-#                                                                     #
-#                         RUN NJOY PROCESSING                         #
-#                                                                     #
-#######################################################################
-#######################################################################
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Skip NJOY calculations if INPUT_LIST is not set (no ENDF-6 file to be processed)
-# Run this part only if XSDIR is given.
-# Produce xsdir lines in parallel.
-# Each line is written in parallel to a temporary file.
-# When the parallel runs are finished, the content of the temporary 
-# file is appended to the xsdir before being deleted.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-RUNJNOYFOLDER="$(pwd)/processing"
-if [[ ! -z $INPUT_LIST ]]
-then
-   INPUT_LIST="$(realpath $INPUT_LIST)"
-   mkdir -p $RUNJNOYFOLDER
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Copy the xsdir to the current working directory.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-   echo -e "\nCopy xsdir '$XSDIR' to '$RUNJNOYFOLDER/xsdir'."
-   cp -rf "$XSDIR" "$RUNJNOYFOLDER/xsdir" 2>/dev/null
-   XSDIR="$RUNJNOYFOLDER/xsdir"
-   ( cd $RUNJNOYFOLDER && $RUNNJOYPARALLEL "$INPUT_LIST" --xsdir "$XSDIR" $ACEONLY $NNJOY )
-   TMPXSDIR="$RUNJNOYFOLDER/.tmp.xsdir"
-   TMPACE="$RUNJNOYFOLDER/.tmp.ace"
-   rm -f "$TMPXSDIR" "$TMPACE" && touch "$TMPXSDIR" "$TMPACE"
-   export TMPXSDIR TMPACE
-   export -f run_xsdir
-   $PARALLEL run_xsdir {} ::: $(find $(pwd) -type f -name "*\.XSDIR")
-   ACEPATH="$RUNJNOYFOLDER/ACEs"
-   mkdir -p "$ACEPATH"
-   echo -e "\nInclude the following ace files for the MCNP benchmarking:"
-   while read -r line # I could use GNU parallel
-   do
-      echo "$ACEPATH/$(basename $line)"
-      ln -fs $line "$ACEPATH/$(basename $line)"
-   done < "$TMPACE"
-   echo -e "\nAdd/Replace the following lines to xsdir file '$XSDIR':"
-   while READ -R LINE # i COULD USE gnu PARALLEl
-   do
-      echo -e "$line"
-      PATTERN=$( echo "$line" | awk '{print $1}')
-      COUNT=$(grep -c "$PATTERN" "$XSDIR")
-      [[ $COUNT -eq 0 ]] && COMMAND="$COMMAND -e '$ a\ $line'" || COMMAND="$COMMAND -e 's|.*${PATTERN}.*|$line|g'"
-   done < "$TMPXSDIR"
-   [[ -z $COMMAND ]] || { COMMAND="sed -i $COMMAND $XSDIR"; eval "$COMMAND";}
-   rm -f "$TMPXSDIR" "$TMPACE"
-   export DATAPATH="$ACEPATH"
-fi
-
-
 
 
 
@@ -396,19 +228,13 @@ fi
 #                                                                     #
 #######################################################################
 #######################################################################
-for B in ${BMARKS[@]}
+echo -e "\nCheck xsdir entries for benchmark suite..."
+ISO=($(grep  -vh "^[Cc]" ${FILELIST[@]} | grep -o "[0-9]\{4,6\}\.[0-9]\{2\}[cC]" | sort | uniq))
+for iso in ${ISO[@]}
 do
-   B="$(realpath $B)"
-   echo -e "\nCheck xsdir entries for benchmark suite in file '$B'..."
-   ISO=( $(grep -oh "^[^c].*[0-9]\{5\}\.03[cC]" "$B" | grep -o "[0-9]\{5\}\.03[cC]" | sort | uniq | cut -d. -f1) )
-   for iso in ${ISO[@]}
-   do
-      COUNT=$(grep -c "${iso}\.03[cC]" "$XSDIR")
-      [[ $COUNT -lt 1 ]] && {>&2 echo -e "ERROR: Missing entry for '${iso}.03c' in xsdir file.";EFLAG=1;}
-   done
-   [[ -z $EFLAG ]] || exit 1
-   echo -en "\e[1A"; echo -e "\e[0K\rAll requested xsdir entries for benchmark suite in file '$B' are present."
-   RUNMCNPFOLDER="$(pwd)/benchmarking/$(basename $B)"
-   mkdir -p $RUNMCNPFOLDER
-   (cd $RUNMCNPFOLDER && $RUNMCNPPARALLEL "$XSDIR" "$B" $NMCNP $TASKS )
+  grep -q "${iso::-1}[cC]" "$XSDIR" || {>&2 echo -e "ERROR: Missing entry for '$iso' in xsdir file.";exit 1;}
 done
+echo -en "\e[1A"; echo -e "\e[0K\rAll requested xsdir entries for benchmark suite are present."
+
+export -f run_mcnp_parallel
+( cd $CWD && $PARALLEL "run_mcnp_parallel {} $XSDIR" ::: ${FILELIST[@]} )
